### ISSUE TITLE
Handle YouTube videos that are too long gracefully

### ISSUE THREAD

**Issue by maxwofford** [hackclub/youtube-dl-bot#4]
<img width="435" alt="Screen Shot 2021-04-20 at 09 42 15" src="https://user-images.githubusercontent.com/5891442/115405965-b8209a00-a1bc-11eb-933b-3760bf88f6d4.png">

Sometimes the bot will fail & leave a beachball loading reaction indefinitely. Would be nice to have a series of reactions for different failure messages.

**Comment by sampoder** [comment]
I've called in the big hands no more issues
